# 1. 스칼라와 벡터 알아보기

In [ ]:
import numpy as np

scalar = np.array(43)
print(scalar)

43


In [ ]:
vector = np.array([32, 33])
print(vector)

[32 33]


In [ ]:
vector.ndim

1

# 2. 행렬 알아보기

## 2.2 행렬의 랭크: 열(행)벡터 중 선형독립인 벡터의 수

In [ ]:
import numpy as np

# 1차원 배열 만들기
v1 = np.array([1, 2, 3, 4])
np.linalg.matrix_rank(v1)

1

해설: 1차원 배열, 즉 하나의 벡터이므로 무조건 선형 독립 

In [ ]:
v2 = np.full((1, 3), 0)
np.linalg.matrix_rank(v2)

0

해설: 0벡터의 랭크는 0

In [ ]:
c = np.array([[1, 2, 4], [2, 4, 8]])
np.linalg.matrix_rank(c)

1

해설: 두번째 행은 선형종속이므로 랭크는 1

### 선형독립 여부 확인하기: 행렬식 이용

In [ ]:
c1 = np.array([[1, 2, 4], [2, 4, 8], [3, 4, 5]])
np.linalg.det(c1)

0.0

해설: 행렬식 계산값이 0이면 선형종속

## 2.3 축 이해하기 
원소들이 축에 따라 어떻게 배치되는가?

In [ ]:
# 1차원 축
a = np.arange(1, 10)
np.sum(a, axis=0)

45

In [ ]:
# 2차원 축
A = np.array([[2, 3], [4, 5]])
np.sum(A, axis=0)

array([6, 8])

해설: axis=0은 수직방향으로 계산.

In [ ]:
np.sum(A, axis=1)

array([5, 9])

해설: axis=1은 수평방향으로 계산.

<배열의 축 변환하기> 
1. transpose
2. rollaxis
3. swapaxes


In [ ]:
# 1. transpose
t = np.arange(3*4*2)
print(t.shape)

t1 = np.reshape(t, (3, 4, 2))
print(t1.shape)

t2 = t1.transpose(0, 2, 1)
print(t2.shape)

(24,)
(3, 4, 2)
(3, 2, 4)


In [ ]:
# 2. rollaxis 
ra = np.ones((3, 4, 5, 6))
print(ra.shape)

ra1 = np.rollaxis(ra, 3, 1)
print(ra1.shape)

(3, 4, 5, 6)
(3, 6, 4, 5)


In [ ]:
# 3. swapaxes
print(ra.shape)

ra2 = np.swapaxes(ra, 2, 1)
print(ra2.shape)

(3, 4, 5, 6)
(3, 5, 4, 6)


## 2.4 배열 확장 및 축소하기
<확장>  

expand_dims

<축소: 2차원 -> 1차원> 
1. .flatten() --copy
2. .ravel() --view
    

In [ ]:
# 확장
x = np.array([1, 2])
print(x.shape)
print(x)

y = np.expand_dims(x, axis=1)
print(y.shape)
print(y)

z = np.expand_dims(x, axis=0)
print(z.shape)
print(z)

(2,)
[1 2]
(2, 1)
[[1]
 [2]]
(1, 2)
[[1 2]]


In [ ]:
# 축소
x = np.arange(0, 10).reshape(2, 5)
print(x.shape)

print(x.flatten().shape)
print(np.may_share_memory(x.flatten(), x))

print(x.ravel().shape)
print(np.may_share_memory(x.ravel(), x))

(2, 5)
(10,)
False
(10,)
True


# 3. 행렬의 종류 알아보기


In [ ]:
# 정사각행렬
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.shape

(3, 3)

In [ ]:
# 대각행렬
b = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
print(b)
print(b.diagonal())

[[1 0 0]
 [0 3 0]
 [0 0 5]]
[1 3 5]


In [ ]:
# 대각행렬 위치 참조하기
c = np.diag(np.arange(1, 4))
print(c)

# 주대각선보다 하나 위에 대각선을 구성하도록 대각행렬 만들기
d = np.diag(np.arange(1, 4), k=1)
print(d)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [ ]:
# 단위행렬
h = np.eye(3, 3)
print(h)

i = np.eye(3, 3, k=2)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 항등행렬: 하나의 정수를 받아서 정사각행렬을 만들고 주대각선 원소의 값만 1로 설정
l = np.identity(3)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 하삼각행렬: 
a = np.arange(1, 10).reshape(3, 3)
print(np.tril(a))
print(np.tril(a, k=-1))

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[0 0 0]
 [4 0 0]
 [7 8 0]]


In [ ]:
# 상삼각행렬:
b = a
print(np.triu(b))
print(np.triu(b, k=1))

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[0 2 3]
 [0 0 6]
 [0 0 0]]


In [ ]:
# 삼각행렬의 전치
c = np.triu(a)
print(c)
print(c.T)

d = np.tril(a)
print(d)
print(d.T)

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [2 5 0]
 [3 6 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 4 7]
 [0 5 8]
 [0 0 9]]


In [ ]:
# 삼각해열의 곱셈
print(c * c)
print(c * d)

[[ 1  4  9]
 [ 0 25 36]
 [ 0  0 81]]
[[ 1  0  0]
 [ 0 25  0]
 [ 0  0 81]]


In [ ]:
# 영행렬
z = np.zeros((3, 3))
print(z)

z1 = np.zeros_like(np.arange(1, 10).reshape(3, 3))
print(z1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# 임의의 값으로 행렬 생성하기: 현재 메모리에 있는 상태의 값 이용
e = np.empty(3)
print(e)

[1. 1. 1.]


In [64]:
# 대칭행렬인지 확인하기: 
# 대칭행렬이라면 원본행렬과 전치한 행렬이 같으므로 
# 원본행렬과 전치한 행렬의 원소가 모두 같은지 알아본다. 
X = np.array([[1, 2, 3], [2, 3, 5], [3, 5, 6]])

print(np.array_equal(X, X.T))
print(np.array_equiv(X, X.T))

True
True


In [2]:
from os.path import join
from google.colab import drive

ROOT = '/content/drive'
drive.mount(ROOT)

Mounted at /content/drive


In [3]:
!pwd

/content


In [4]:
!ls /content/drive/MyDrive/numpy_for_deep_learning_and_machine_learning

Chapter1.ipynb	Chapter2.ipynb	numpy_for_deep_learning


In [5]:
PROJ = "/drive/MyDrive/numpy_for_deep_learning_and_machine_learning"
PROJ_PATH = join(ROOT, PROJ)

In [6]:
import os, sys

sys.path.insert(0, PROJ_PATH)

In [7]:
%cd /content/drive/MyDrive/numpy_for_deep_learning_and_machine_learning

/content/drive/MyDrive/numpy_for_deep_learning_and_machine_learning


In [8]:
!pwd

/content/drive/MyDrive/numpy_for_deep_learning_and_machine_learning


In [17]:
!rm -rf numpy_for_deep_learning/

In [18]:
!git remote add origin https://github.com/ahjin-vision/numpy_for_deep_learning.git

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


In [12]:
!git config --global user.email "ahjin.vision@gmail.com"
!git config --global user.name "ahjin-vision"

In [13]:
!ls

Chapter1.ipynb	Chapter2.ipynb	numpy_for_deep_learning


In [14]:
!git add Chapter2.ipynb

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


In [15]:
!pwd

/content/drive/MyDrive/numpy_for_deep_learning_and_machine_learning
