<a href="https://colab.research.google.com/github/ahjin-vision/numpy_for_deep_learning/blob/main/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Chapter 1. 파이썬과 넘파이 모듈 차이점 이해하기 

##1. 배열구조 이해하기

In [ ]:
l = [1, 2, 3]
l = [[1, 2, 3], [4, 5, 6]]

In [ ]:
for i, a in enumerate(l):
    for j, b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [ ]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [ ]:
l = [1, 2, 3, 4]
a = np.array(l)   # list -> ndarray
a          # >> array([1, 2, 3, 4]); 저장된 다차원배열 반환
type(a)    # >> numpy.ndarray: 클래스 확인

# 데이터를 관리하는 속성
a.data     # >> <memory at 0x7f207bf5d1f0>: 메모리에 저장된 레퍼런스 출력
a.data.obj # >> array([1, 2, 3, 4]): 다차원배열의 값 반환
type(a.data)        # >> memoryview
type(a.data.obj)    # >> numpy.ndarray

numpy.ndarray

In [ ]:
# 새로운 변수에 할당 후 갱신
b = a       # 다차원배열을 새 변수에 할당
b[0] = 100  # 새 변수에 저장된 첫번째 원소 갱신 
b           # >> array([100,   2,   3,   4])
a           # >> array([100,   2,   3,   4]): 원본 다차원배열까지 갱신됨. 

array([100,   2,   3,   4])

In [ ]:
# 복사 후 갱신
c = np.array(a)   # 다차원배열의 객체를 array함수에 넣어서 새 다차원배열 생성. 
c[0] = 99         # 새 다차원배열에 저장된 첫번째 원소 갱신. 
c                 # >> array([99,  2,  3,  4])
a                 # >> array([1, 2, 3, 4]): 원본 다차원배열 유지. 

array([1, 2, 3, 4])

In [ ]:
d = np.array(l, dtype=np.float)
d

array([1., 2., 3., 4.])

In [ ]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.shape          # >> (2, 3): 원소의 개수 조회. 2개의 축을 가지므로 2개의 원소를 가진 튜플로 반환. 
a2.ndim           # >> 2: 축의 개수 조회. 2개의 축을 가지므로 2차원이라는 뜻. 
a2.dtype          # >> dtype('int64'): 배열이 구성된 클래스 확인 
a2.itemsize       # >> 8: 원소의 byte 단위 조회. 8byte = 64bit (1 byte = 8 bit)
a2.size           # >> 6: 모든 원소의 개수 조회. 
a2.strides        # >> (24, 8): 배열을 확장할 때의 기준정보 조회. (하나의 행의 전체 크기(길이), 하나의 원소의 크기)

(24, 8)

In [ ]:
# 1차원 배열의 원소 검색: 하나의 원소 검색 
# 색인연산자인 대괄호 안에 정수 전달
l = [1, 2, 3, 4]      # 리스트
a = np.array(l)       # 다차원배열

print(l[0])
print(a[0]) 

1
1


In [ ]:
# 2차원 배열의 원소 검색: 하나의 원소 검색
l2 = [[1, 2, 3], [4, 5, 6]]
a2 = np.array(l2)

# 2차원 리스트의 원소 검색: 색인연산 2번 사용 
print(l2[0][1])

# 2차원배열의 원소검색: 색인연산자인 대괄호 안에 행과 열의 인덱스를 튜플(쉼표로 구분해서. 튜플괄호는 생략 可)로 전달 
print(a2[0, 1])
print(type(a2[0, 1]))         # >> <class 'numpy.int64'> <- 넘파이모듈의 정수 클래스 
print(a2[0, 1].item())
print(type(a2[0, 1].item()))  # >> <class 'int'>         <- 파이썬 정수 클래스

2
2
<class 'numpy.int64'>
2
<class 'int'>


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
a.data           # >> <memory at 0x7fd6d732bc80>: 메모리에 저장된 객체 정보

b = memoryview(a)
b                # >> <memory at 0x7fd6cea3cae0>

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.data.hex()

'0100000000000000020000000000000003000000000000000400000000000000'

In [ ]:
len(a.data.tobytes())

32

In [ ]:
original = np.array([1, 2, 3, 4], dtype=np.float_)
frombuffer = np.frombuffer(original)    # 배열을 복사하지 않고 공유하기. 자료형을 지정하지 않은 배열을 인자로 넘기면 값이 다르게 표현됨. 

# 같은 배열을 공유하는지 확인
print(original, frombuffer)  # >> [1. 2. 3. 4.] [1. 2. 3. 4.]

# frombuffer()의 특징
frombuffer.flags             # >> OWNDATA: False :스스로가 원본이 아닌 view임을 뜻함. 
frombuffer[0] = 100
print(original, frombuffer)  # frombuffer 갱신 시 원본데이터도 같이 갱신됨. 

base = frombuffer.base       # .base 속성으로 원본데이터를 메모리에 저장
base is original             # >> True: 원본배열과 레퍼런스가 같은지 확인
base.flags                   # >> OWNDATA: True 
print(original, frombuffer, base)    # >> [100.   2.   3.   4.] [100.   2.   3.   4.] [100.   2.   3.   4.]
base[0] = 50
print(original, frombuffer, base)    # >> [50.  2.  3.  4.] [50.  2.  3.  4.] [50.  2.  3.  4.]  ?????????

[1. 2. 3. 4.] [1. 2. 3. 4.]
[100.   2.   3.   4.] [100.   2.   3.   4.]
[100.   2.   3.   4.] [100.   2.   3.   4.] [100.   2.   3.   4.]
[50.  2.  3.  4.] [50.  2.  3.  4.] [50.  2.  3.  4.]


##2. 넘파이 모듈 함수의 특징

In [ ]:
a = np.zeros((2, 3), dtype=np.int_)
a != 0

NameError: ignored

In [ ]:
(a != 0).any
np.any

NameError: ignored

In [ ]:
numpy_module = set(dir(np))
ndarray_class = set(dir(np.ndarray))
interjection = numpy_module & ndarray_class

# 동일한 함수/메소드 이름을 가진 것들의 수: 
len(interjection)   # >> 48 

# 출력 
count = 0
for i in list(interjection):
    count += 1
    print(i, end= " ")
    if count % 5 == 0:
        print()

In [ ]:
set(dir(np))

In [ ]:
# 일반함수에는 없고 유니버설 함수에만 있는 속성이나 메소드 확인하기 
import numpy as np 

set(dir(np.add)) - set(dir(np.sort))

{'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types'}

차원 추가하기: 실제 축을 하나 추가하는 것.
1. np.newaxis
2. .reshape( )


In [ ]:
# 차원 추가하기: 
# np.newaxis: 축을 하나 추가하는 것.

# 1차원 배열 -(수평축 하나 추가)-> 2차원 배열
a = np.arange(6, 10)
b = np.arange(10, 14)
c = a[:, np.newaxis]
print(c.shape)
>>> (4, 1)

# 1차원 배열 -(수직축 하나 추가)-> 2차원 배열
d = b[np.newaxis, :]
print(d.shape)
>>> (1, 4)

(4, 1)
[[6]
 [7]
 [8]
 [9]]
(1, 4)
[[10 11 12 13]]


In [ ]:
# .reshape() 이용하는 방법 

a = np.arange(1, 7)
a = a.reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

## 3. 배열 할당과 검색

In [ ]:
a = np.array([[1, 2], [3, 4]])
print('원본배열', '\n',  a)

# alias
b = a
print('alias', '\n', b)
print('원본배열 레퍼런스와 alias 레퍼런스 비교: ', a is b)  # true. b가 갱신되면 a도 갱신됨. 

# 부분배열
c = a[:]
print('부분배열', '\n', c)
print('원본배열 레퍼런스와 부분배열 레퍼런스 비교: ', a is c)  # false. but c가 갱신되면 a 갱신 

# 사본
d = a.copy()
print('사본', '\n', d)
print('원본배열 레퍼런스와 사본 레퍼런스 비교: ', a is d)  # false. c가 갱신되더라도 a는 갱신되지 않음. 

원본배열 
 [[1 2]
 [3 4]]
alias 
 [[1 2]
 [3 4]]
원본배열 레퍼런스와 alias 레퍼런스 비교:  True
부분배열 
 [[1 2]
 [3 4]]
원본배열 레퍼런스와 부분배열 레퍼런스 비교:  False
사본 
 [[1 2]
 [3 4]]
원본배열 레퍼런스와 사본 레퍼런스 비교:  False


In [ ]:
b[1][1] = 10
print(b)
print(a)


c[1][1] = 99
print(c)
print(a)

d[1][1] = 100
print(d)
print(a)

[[ 1  2]
 [ 3 10]]
[[ 1  2]
 [ 3 10]]
[[ 1  2]
 [ 3 99]]
[[ 1  2]
 [ 3 99]]
[[  1   2]
 [  3 100]]
[[ 1  2]
 [ 3 99]]


In [ ]:
# base 확인: 부분배열은 원본배열의 view를 제공한다. 
print('alias의 base', '\n', b.base)
print('alias의 base 레퍼런스와 원본레퍼런스 비교', '\n', a is b.base)  # false

print('부분배열의 base', '\n', c.base)
print('부분배열의 base 레퍼런스와 원본레퍼런스 비교', '\n', a is c.base) # true

print('사본의 base', '\n', d.base)
print('사본의 base 레퍼런스와 원본레퍼런스 비교', '\n', a is d.base)    # false

alias의 base 
 None
alias의 base 레퍼런스와 원본레퍼런스 비교 
 False
부분배열의 base 
 [[1 2]
 [3 4]]
부분배열의 base 레퍼런스와 원본레퍼런스 비교 
 True
사본의 base 
 None
사본의 base 레퍼런스와 원본레퍼런스 비교 
 False


In [ ]:
# view: 원본 배열을 슬라이싱 핳 때 새로운 객체가 생기지만 데이터는 원본과 공유한다. 
arr = np.arange(8).reshape(2, 4)
print('원본배열', '\n', arr)

sliced_arr = arr[0]
print('부분배열', '\n', sliced_arr) 

# 부분배열은 복사가 아니라 참조이기 때문에 갱신시 원본도 갱신됨. (원본 갱신시에도 부분배열 갱신)
# 리스트의 슬라이싱은 복사! 
arr[0] = 10
print('원본배열', '\n', arr)
print('부분배열', '\n', sliced_arr) 

원본배열 
 [[0 1 2 3]
 [4 5 6 7]]
부분배열 
 [0 1 2 3]
원본배열 
 [[10 10 10 10]
 [ 4  5  6  7]]
부분배열 
 [10 10 10 10]


In [ ]:
arr_copy1 = arr[0].copy()
arr_copy2 = np.array(arr[0], copy=True)

arr[0] = 100
print('원본배열', '\n', arr)
print('부분배열복사1', '\n', arr_copy1) 
print('부분배열복사2', '\n', arr_copy2) 

# view 만들기 2: 
arr_view = arr.view()
np.may_share_memory(arr, arr_view)

원본배열 
 [[100. 100. 100. 100.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]
부분배열복사1 
 [100. 100. 100. 100.]
부분배열복사2 
 [100. 100. 100. 100.]


True

In [ ]:
# cf. np.asarray() vs np.array()
arr = np.ones((3,4))
print('원본배열', '\n', arr)

asarray = np.asarray(arr)   # 참조본 생성
array = np.array(arr)       #복사본 생성

arr[0]=0
print('asarray, 참조본', '\n', asarray)
print('array, 복사본', '\n', array)

원본배열 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
asarray, 참조본 
 [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array, 복사본 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
